### ISSUE TITLE
DNS timeout

### ISSUE THREAD

**Issue by DF001** [dirkjanm/BloodHound.py#126]
Getting this error constantly that doesn't allow me to even use bloodhound-python:
 ``` 
bloodhound-python -u svc_loanmgr -p Moneymakestheworldgoround! -d EGOTISTICALBANK.LOCAL -ns 10.10.10.175
Traceback (most recent call last):
  File "/usr/bin/bloodhound-python", line 33, in <module>
    sys.exit(load_entry_point('bloodhound==1.6.0', 'console_scripts', 'bloodhound-python')())
  File "/usr/lib/python3.10/site-packages/bloodhound/__init__.py", line 303, in main
    ad.dns_resolve(domain=args.domain, options=args)
  File "/usr/lib/python3.10/site-packages/bloodhound/ad/domain.py", line 645, in dns_resolve
    q = self.dnsresolver.query(query, 'SRV', tcp=self.dns_tcp)
  File "/usr/lib/python3.10/site-packages/dns/resolver.py", line 1110, in query
    return self.resolve(qname, rdtype, rdclass, tcp, source,
  File "/usr/lib/python3.10/site-packages/dns/resolver.py", line 1066, in resolve
    timeout = self._compute_timeout(start, lifetime,
  File "/usr/lib/python3.10/site-packages/dns/resolver.py", line 879, in _compute_timeout
    raise LifetimeTimeout(timeout=duration, errors=errors)
dns.resolver.LifetimeTimeout: The resolution lifetime expired after 3.202 seconds: Server 10.10.10.175 UDP port 53 answered The DNS operation timed out.; Server 10.10.10.175 UDP port 53 answered The DNS operation timed out. 
```

**Comment by zoceanyq** [comment]
Hello, have you solved this problem? I also encountered the same problem as you.

**Comment by Malshift** [comment]
If you're having this issue use `--dns-timeout <time in seconds e.g (5)>` the default is 3.

**Comment by dirkjanm** [comment]
As specified above, please use the `--dns-timeout` parameter and set it to a higher value.
