### ISSUE TITLE
Bug when -d is not specified

### ISSUE THREAD

**Issue by CaledoniaProject** [dirkjanm/BloodHound.py#129]
```
# bloodhound-python -u user@xxx.com -p xxx -c All,LoggedOn

/usr/local/lib/python3.6/dist-packages/OpenSSL/crypto.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography import utils, x509
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/bloodhound/__init__.py", line 269, in main
    auth = ADAuthentication(username=args.username, password=args.password, domain=args.domain, auth_method=args.auth_method)
  File "/usr/local/lib/python3.6/dist-packages/bloodhound/ad/authentication.py", line 52, in __init__
    self.domain = domain.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by dirkjanm** [comment]
This looks like an old version. If you can reproduce this with the latest version I can have a look but this may be a bug that is already fixed in the latest version.

**Comment by CaledoniaProject** [comment]
I installed it via pip, should I try with github instead?

**Comment by dirkjanm** [comment]
pip is fine but that should give you a newer version than what that output is from

**Comment by quibbitlabs** [comment]
I can confirm that this is an issue both in pip and the github version. I will open a PR resolving this
