### ISSUE TITLE
`-no-pass` flag is not working

### ISSUE THREAD

**Issue by Pri3st** [dirkjanm/BloodHound.py#141]
When I try to use the `-k -no-pass` flag, `bloodhound-python` keeps asking for a password.

```
# echo $KRB5CCNAME                                                                         
/home/<REDACTED>.ccache

# bloodhound-python -u <REDACTED> -k -no-pass -ns <REDACTED> -d <REDACTED> -c All --zip
Password:
```

Same when I specify the **Kerberos** authentication exclusively.
```
# bloodhound-python -u <REDACTED> -k -no-pass -ns <REDACTED> -d <REDACTED> --auth-method kerberos
Password:
```

If I insert a null password, I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bloodhound/__init__.py", line 338, in main
    bloodhound.run(collect=collect,
  File "/usr/local/lib/python3.11/dist-packages/bloodhound/__init__.py", line 79, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect, cache_computers=do_computer_enum)
  File "/usr/local/lib/python3.11/dist-packages/bloodhound/ad/domain.py", line 523, in prefetch_info
    self.get_objecttype()
  File "/usr/local/lib/python3.11/dist-packages/bloodhound/ad/domain.py", line 240, in get_objecttype
    self.ldap_connect()
  File "/usr/local/lib/python3.11/dist-packages/bloodhound/ad/domain.py", line 69, in ldap_connect
    ldap = self.ad.auth.getLDAPConnection(hostname=self.hostname, ip=ip,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bloodhound/ad/authentication.py", line 109, in getLDAPConnection
    bound = conn.bind()
            ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ldap3/core/connection.py", line 635, in bind
    raise LDAPUnknownAuthenticationMethodError(self.last_error)
ldap3.core.exceptions.LDAPUnknownAuthenticationMethodError: NTLM needs domain\username and a password
```

**Comment by redt1de** [comment]
I am also having this issue.

**Comment by dirkjanm** [comment]
should be fixed thanks to @lefayjey in the latest version on git
