### ISSUE TITLE
Could not find the requested domain

### ISSUE THREAD

**Issue by blabut** [dirkjanm/BloodHound.py#145]
Hi,

I am trying to use `bloodhound-python` for a regular domain enumeration routine.

Here is the (anonymised) output showing my error:

```bash
[Oct 17, 2023 - 15:00:02 (CEST)] exegol-tp-ad 04_Data # bloodhound-python -u 'username' -p 'password' -d domain.name -dc dcname
WARNING: Could not find a global catalog server, assuming the primary DC has this role
If this gives errors, either specify a hostname with -gc or disable gc resolution with --disable-autogc
INFO: Getting TGT for user
WARNING: Failed to get Kerberos TGT. Falling back to NTLM authentication. Error: Kerberos SessionError: KDC_ERR_C_PRINCIPAL_UNKNOWN(Client not found in Kerberos database)
INFO: Connecting to LDAP server: coruscant
ERROR: Could not find the requested domain domain.name on this DC, LDAP server reports is domain as domain.name (you may want to try that?)
Traceback (most recent call last):
  File "/root/.local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/root/.local/pipx/venvs/bloodhound/lib/python3.9/site-packages/bloodhound/__init__.py", line 338, in main
    bloodhound.run(collect=collect,
  File "/root/.local/pipx/venvs/bloodhound/lib/python3.9/site-packages/bloodhound/__init__.py", line 79, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect, cache_computers=do_computer_enum)
  File "/root/.local/pipx/venvs/bloodhound/lib/python3.9/site-packages/bloodhound/ad/domain.py", line 524, in prefetch_info
    self.get_domains(acl=acls)
  File "/root/.local/pipx/venvs/bloodhound/lib/python3.9/site-packages/bloodhound/ad/domain.py", line 291, in get_domains
    raise CollectionException("Specified domain was not found in LDAP")
bloodhound.ad.utils.CollectionException: Specified domain was not found in LDAP
```

I am using the newest version of the tool I installed with pip3 in an Exegol container. I also checked that both `dcname` and `domain.name` both resolved when pinged from the same container. Am I doing anything wrong here ? 

Thanks a lot !

**Comment by dirkjanm** [comment]
Well it can't find that domain on the host you're talking to. If the domains in the following line differ, then you are talking to the wrong DC:

```
ERROR: Could not find the requested domain domain.name on this DC, LDAP server reports is domain as domain.name (you may want to try that?)
```

Note that `-dc` takes a full hostname, and a netbios (short) name might result in it resolving the wrong host.
