### ISSUE TITLE
AttributeError: install_layout

### ISSUE THREAD

**Issue by jsdhasfedssad** [dirkjanm/BloodHound.py#152]
Hi,

I was trying to install your tool using python setup.py install on Kali 2023.4 today but I got the below error. 

/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
Traceback (most recent call last):
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ffxnfk74/impacket-0.11.0/setup.py", line 52, in <module>
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 296, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout. Did you mean: 'install_platlib'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pentest/bloodhound.py/setup.py", line 3, in <module>
    setup(name='bloodhound',
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/install.py", line 140, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 466, in run
    self.easy_install(spec, not self.no_deps)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 714, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 764, in install_item
    self.process_distribution(spec, dist, deps)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 812, in process_distribution
    distros = WorkingSet([]).resolve(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
    dist = best[req.key] = env.best_match(
                           ^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
    return self.obtain(req, installer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
    return installer(requirement)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 737, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 762, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 956, in install_eggs
    return self.build_and_install(setup_script, setup_base)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 1230, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 1216, in run_setup
    run_setup(setup_script, args)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 190, in setup_context
    with save_modules():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ffxnfk74/impacket-0.11.0/setup.py", line 52, in <module>
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 296, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pentest/bloodhound.py/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout

Update 1: The installation works if "pip install ." is used instead of "python setup.py install".

**Comment by dirkjanm** [comment]
I'll make sure to update the readme to remove references to the `setup.py install` command, but none of the errors in the stacktrace above are related to bloodhound.py code so it's likely some dependencies that break
