### ISSUE TITLE
Error when using bloodhound-python

### ISSUE THREAD

**Issue by kkeennyy-tan** [dirkjanm/BloodHound.py#161]
Hello all,

Im just experiencing error when doing HTB labs. 

I already did uninstall bloodhound `sudo pip3 uninstall bloodhound` and reinstall bloodhound `sudo pip2 install bloodhound`

`bloodhound-python -u svc-alfresco -p s3rvice -d htb.local -ns 10.10.10.161
Traceback (most recent call last):
  File "/usr/bin/bloodhound-python", line 33, in <module>
    sys.exit(load_entry_point('bloodhound==1.7.2', 'console_scripts', 'bloodhound-python')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bloodhound/__init__.py", line 308, in main
    ad.dns_resolve(domain=args.domain, options=args)
  File "/usr/lib/python3/dist-packages/bloodhound/ad/domain.py", line 699, in dns_resolve
    q = self.dnsresolver.query(query, 'SRV', tcp=self.dns_tcp)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1364, in query
    return self.resolve(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1321, in resolve
    timeout = self._compute_timeout(start, lifetime, resolution.errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1075, in _compute_timeout
    raise LifetimeTimeout(timeout=duration, errors=errors)
dns.resolver.LifetimeTimeout: The resolution lifetime expired after 3.105 seconds: Server Do53:10.10.10.161@53 answered The DNS operation timed out.`

**Comment by dirkjanm** [comment]
Try setting `--dns-timeout` to a higher value, like 30. And make sure it's using the correct DNS server, etc

**Comment by kkeennyy-tan** [comment]
@dirkjanm  is this correct adding --dns-timeout to my /etc/resolv.conf
I tried to research how to add `--dns-timeout` to my local kali

`domain localdomain
search localdomain
nameserver 192.168.186.2
--dns-timeout 30`

but tried to run the bloodhound-python
`bloodhound-python -u svc-alfresco -p s3rvice -d htb.local -ns 10.10.10.161            
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 5, in <module>
    from bloodhound import main
  File "/home/cheesemiss/.local/lib/python2.7/site-packages/bloodhound/__init__.py", line 27, in <module>
    from bloodhound.ad.domain import AD, ADDC
  File "/home/cheesemiss/.local/lib/python2.7/site-packages/bloodhound/ad/domain.py", line 190
    yield from self.search(search_filter, attributes, search_base, generator, use_gc, use_resolver, query_sd, is_retry=True)
             ^
SyntaxError: invalid syntax`


I have internet access to my kali

**Comment by dirkjanm** [comment]
@kkeennyy-tan you are trying to run bloodhound with python 2.7 in the above stack trace while bloodhound.py supports python 3 only
