### ISSUE TITLE
AttributeError: Module Collections

### ISSUE THREAD

**Issue by th3g3ntl3m4n84** [dirkjanm/BloodHound.py#166]
Hello,
I've been having a problem to execute the Bloodhound.py on python3.10 our above because this error message:
`$ bloodhound-python -h
Traceback (most recent call last):
  File "/home/th3g3ntl3m4n/.local/bin/bloodhound-python", line 6, in <module>
    from bloodhound import main
  File "/home/th3g3ntl3m4n/.local/lib/python3.10/site-packages/bloodhound/__init__.py", line 27, in <module>
    from bloodhound.ad.domain import AD, ADDC
  File "/home/th3g3ntl3m4n/.local/lib/python3.10/site-packages/bloodhound/ad/domain.py", line 32, in <module>
    from ldap3 import ALL_ATTRIBUTES, BASE, SUBTREE, LEVEL
  File "/home/th3g3ntl3m4n/.local/lib/python3.10/site-packages/ldap3/__init__.py", line 254, in <module>
    from .core.server import Server
  File "/home/th3g3ntl3m4n/.local/lib/python3.10/site-packages/ldap3/core/server.py", line 35, in <module>
    from ..protocol.rfc4512 import SchemaInfo, DsaInfo
  File "/home/th3g3ntl3m4n/.local/lib/python3.10/site-packages/ldap3/protocol/rfc4512.py", line 33, in <module>
    from ..utils.conv import escape_bytes, json_hook, check_json_dict, format_json, check_escape
  File "/home/th3g3ntl3m4n/.local/lib/python3.10/site-packages/ldap3/utils/conv.py", line 30, in <module>
    from ..utils.ciDict import CaseInsensitiveDict
  File "/home/th3g3ntl3m4n/.local/lib/python3.10/site-packages/ldap3/utils/ciDict.py", line 31, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'`

I see that this problem occurs because the MutableMapping now is in collections.abc, but I haven't success to fix it with the solutions on the Internet.

![bloodhound-python_error](https://github.com/dirkjanm/BloodHound.py/assets/1410153/3802fe38-9932-4e53-a586-344c2c6f02fb)

Thanks

**Comment by dirkjanm** [comment]
Sounds like an error in ldap3, I recommend downgrading to a previous version
