### ISSUE TITLE
null displayName not handled

### ISSUE THREAD

**Issue by noraj** [dirkjanm/BloodHound.py#170]
```
INFO: Found 3580 users
INFO: Found 405 groups
Traceback (most recent call last):
  File "/usr/bin/bloodhound-python", line 33, in <module>
    sys.exit(load_entry_point('bloodhound==1.7.2', 'console_scripts', 'bloodhound-python')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bloodhound/__init__.py", line 343, in main
    bloodhound.run(collect=collect,
  File "/usr/lib/python3.11/site-packages/bloodhound/__init__.py", line 81, in run
    membership_enum.enumerate_memberships(timestamp=timestamp, fileNamePrefix=fileNamePrefix)
  File "/usr/lib/python3.11/site-packages/bloodhound/enumeration/memberships.py", line 847, in enumerate_memberships
    self.do_container_collection(timestamp, fileNamePrefix)
  File "/usr/lib/python3.11/site-packages/bloodhound/enumeration/memberships.py", line 836, in do_container_collection
    self.enumerate_gpos(timestamp, fileNamePrefix)
  File "/usr/lib/python3.11/site-packages/bloodhound/enumeration/memberships.py", line 449, in enumerate_gpos
    "name": '%s@%s' % (ADUtils.get_entry_property(entry, 'displayName').upper(), self.addomain.domain.upper()),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by dirkjanm** [comment]
hey, appreciate the report. This should be fixable by changing the following on that line:

```
ADUtils.get_entry_property(entry, 'displayName')
```

to

```
ADUtils.get_entry_property(entry, 'displayName', '')
```

instead

**Comment by noraj** [comment]
Indeed, it works with this patched.
