### ISSUE TITLE
None containerdn is not handled

### ISSUE THREAD

**Issue by tarasrudnyk-guardicore** [dirkjanm/BloodHound.py#173]
I encountered an issue with not handling None `containerdn`:
```
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/bloodhound/__init__.py", line 338, in main
    bloodhound.run(collect=collect,
  File "/usr/local/lib/python3.10/site-packages/bloodhound/__init__.py", line 82, in run
    membership_enum.enumerate_memberships(timestamp=timestamp)
  File "/usr/local/lib/python3.10/site-packages/bloodhound/enumeration/memberships.py", line 807, in enumerate_memberships
    self.do_container_collection(timestamp)
  File "/usr/local/lib/python3.10/site-packages/bloodhound/enumeration/memberships.py", line 798, in do_container_collection
    self.enumerate_containers(timestamp)
  File "/usr/local/lib/python3.10/site-packages/bloodhound/enumeration/memberships.py", line 629, in enumerate_containers
    if ADUtils.is_filtered_container_child(ADUtils.get_entry_property(childentry, 'distinguishedName')):
  File "/usr/local/lib/python3.10/site-packages/bloodhound/ad/utils.py", line 427, in is_filtered_container_child
    if "CN=PROGRAM DATA,DC=" in containerdn.upper():
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by tarasrudnyk-guardicore** [comment]
@jchristman just checked that `bloodhound-ce` does not contain this fix. Can you please create a PR for this branch? It should be just cherry-picked from https://github.com/dirkjanm/BloodHound.py/commit/404c215fc3e989f487c91d7bfdb102fbfde5f248

**Comment by dirkjanm** [comment]
I'm still merging some PRs, after which the changes will be merged into the CE branch as well
