### ISSUE TITLE
Kerberos ticket ccache authentication not working

### ISSUE THREAD

**Issue by smokeintheshell** [dirkjanm/BloodHound.py#185]
Attempting to use Kerberos with a ccache and `-k -no-pass` appears to not be working. After reading #141 I updated my BloodHound.py to 1.7.2 and reattempted using an obtained ticket but got the same errors:
```
KRB5CCNAME=<user>.ccache proxychains bloodhound-python -d <target domain> --zip -c All --dns-tcp -ns <DC IP> -dc <DC FQDN> -gc <DC FQDN> -k -no-pass
Traceback (most recent call last):
  File "/home/jkl/.local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/home/jkl/.local/pipx/venvs/bloodhound/lib/python3.10/site-packages/bloodhound/__init__.py", line 297, in main
    auth = ADAuthentication(username=args.username, password=args.password, domain=args.domain, auth_method=args.auth_method)
  File "/home/jkl/.local/pipx/venvs/bloodhound/lib/python3.10/site-packages/bloodhound/ad/authentication.py", line 55, in __init__
    if '@' in self.username:
TypeError: argument of type 'NoneType' is not iterable
```
It looks like when specifying `-k -no-pass` and providing a ccache in `KRB5CCNAME`, `bloodhound-python` isn't using the ticket. If I then specify `-u <UPN>`, I get prompted for a password despite using `-no-pass`:
```
proxychains -q -f ./prox.conf bloodhound-python -d <target domain> --zip -c All --dns-tcp -ns <DC IP> -dc <DC FQDN> -gc <DC FQDN> -k -no-pass -u '<UPN>'
Password: 
```

**Comment by smokeintheshell** [comment]
Additionally, if I use `-u <UPN> -k -no-pass` and enter a blank password or use `-u <UPN> -p '' -k -no-pass`, with or without `--cachefile` I get the following error:
```
proxychains -q -f ./prox.conf bloodhound-python -d <target domain> --zip -c All --dns-tcp -ns <DC IP> -dc <DC FQDN> -gc <DC FQDN> -u <UPN> -p '' -k -no-pass --cachefile <ccache>
INFO: Found AD domain: <target domain>
INFO: Getting TGT for user
WARNING: Failed to get Kerberos TGT. Falling back to NTLM authentication. Error: Kerberos SessionError: KDC_ERR_PREAUTH_FAILED(Pre-authentication information was invalid)
Traceback (most recent call last):
  File "/home/jkl/.local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/home/jkl/.local/pipx/venvs/bloodhound/lib/python3.10/site-packages/bloodhound/__init__.py", line 343, in main
    bloodhound.run(collect=collect,
  File "/home/jkl/.local/pipx/venvs/bloodhound/lib/python3.10/site-packages/bloodhound/__init__.py", line 71, in run
    self.ad.load_cachefile(cachefile)
  File "/home/jkl/.local/pipx/venvs/bloodhound/lib/python3.10/site-packages/bloodhound/ad/domain.py", line 675, in load_cachefile
    cachedata = json.load(cfile)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/codecs.py", line 701, in read
    return self.reader.read(size)
  File "/usr/lib/python3.10/codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 8: invalid start byte
```
Its looking like, no matter I do, the ticket is being completely ignored.

**Comment by gatariee** [comment]
hey, im also having his issue; have you found a solution? @smokeintheshell

**Comment by isfahany** [comment]
Happened to me with the exact version. any update? @gatariee @smokeintheshell

**Comment by gatariee** [comment]
> Happened to me with the exact version. any update? @gatariee @smokeintheshell 
> 

I couldn't get bloodhound.py to work. A workaround would be to use netexec's bloodhound collectors modules instead of bloodhound.py, this has proven more consistent for me.

**Comment by smokeintheshell** [comment]
no update for this on my side specifically with `bloodhound-python`.
workarounds i've used are tunneling a windows box and using sharphound with an injected ticket and using `nxc` as @gatariee mentioned.
It's been a hot minute since I looked into this, but out of curiosity @isfahany are you using a TGT or a ST for the LDAP service on the DC?

**Comment by dirkjanm** [comment]
ccache auth now works properly again, note that you have to explicitly specify a username (which must match with the one in your ccache). Only TGTs are supported in the ccache.

**Comment by jl-sygnia** [comment]
thanks @dirkjanm and @lefayjey for finding and fixing this issue
