### ISSUE TITLE
Resolver error

### ISSUE THREAD

**Issue by Aziz1337** [dirkjanm/BloodHound.py#188]
Hi guys when i am trying to run this command i get an error:
`python3 ~/BloodHound.py/bloodhound.py --dns-tcp -ns  DC-IP -d DOMAIN_NAME -u 'user' -p 'password' -c ALL --dns-timeout 30
`

```
Traceback (most recent call last):
  File "/home/kali/BloodHound.py/bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/home/kali/BloodHound.py/bloodhound/__init__.py", line 308, in main
    ad.dns_resolve(domain=args.domain, options=args)
  File "/home/kali/BloodHound.py/bloodhound/ad/domain.py", line 699, in dns_resolve
    q = self.dnsresolver.query(query, 'SRV', tcp=self.dns_tcp)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1364, in query
    return self.resolve(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1318, in resolve
    (nameserver, tcp, backoff) = resolution.next_nameserver()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 763, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _ldap._tcp.pdc._msdcs.support.htb. IN SRV: Server Do53:10.10.11.174@53 answered SERVFAIL
```
I made sure to add the Ip address to my /etc/hosts file
Can someone help me fix it please !

**Comment by sec1900** [comment]
I encountered the same situation, have you solved this problem?

**Comment by dirkjanm** [comment]
You likely have a wrong DNS host setup. Make sure DNS is working properly. Bloodhound python does NOT use the hosts file.
