### ISSUE TITLE
bloodhound-python  while running this i got some errors

### ISSUE THREAD

**Issue by abhijeet11yadav** [dirkjanm/BloodHound.py#189]
this is command which i run during a ctf 
bloodhound-python -d jab.htb -c all -u svc_openfire -p '!@#$%^&*(1qazxsw' -ns 10.10.11.4 --zip 

i got this error everytime i ahve deleted neo4j and bloohound and reinstall but agian this error is showing while running the above command

Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bloodhound/__init__.py", line 308, in main
    ad.dns_resolve(domain=args.domain, options=args)
  File "/usr/local/lib/python3.11/dist-packages/bloodhound/ad/domain.py", line 699, in dns_resolve
    q = self.dnsresolver.query(query, 'SRV', tcp=self.dns_tcp)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1262, in query
    return self.resolve(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1201, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 704, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _ldap._tcp.pdc._msdcs.jab.htb. IN SRV: Server 10.10.11.4 UDP port 53 answered SERVFAIL

**Comment by dirkjanm** [comment]
The DNS server isn't answering the queries for that domain properly. It may be part of the CTF, or it's your local setup that breaks something. In any case bloodhound-python does rely on a working DNS so this isn't really the tools fault. Maybe a different DNS server would help?

**Comment by 1540935409** [comment]
我开了代理的tun模式会导致这样 不知道怎么解决这个dns冲突
