### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 8: invalid start byte When specifying Cache file to use

### ISSUE THREAD

**Issue by chencohen3** [dirkjanm/BloodHound.py#191]
hey there
I've been trying to use Bloodhound python with a generated ticket by impacket getTGT(https://github.com/fortra/impacket/blob/master/examples/getTGT.py)

Once I try to use the ticket I'm getting the following error:

`bloodhound-python -c ALL -u <username> -d <domain> -dc <dc ip> --use-ldaps -k -no-pass --cachefile <user>.ccache 
Password: 
INFO: Found AD domain: company.com
INFO: Getting TGT for user
WARNING: Failed to get Kerberos TGT. Falling back to NTLM authentication. Error: Kerberos SessionError: KDC_ERR_PREAUTH_FAILED(Pre-authentication information was invalid)
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 33, in <module>
    sys.exit(load_entry_point('bloodhound==1.7.2', 'console_scripts', 'bloodhound-python')())
  File "/usr/local/lib/python3.7/site-packages/bloodhound-1.7.2-py3.7.egg/bloodhound/__init__.py", line 350, in main
  File "/usr/local/lib/python3.7/site-packages/bloodhound-1.7.2-py3.7.egg/bloodhound/__init__.py", line 71, in run
  File "/usr/local/lib/python3.7/site-packages/bloodhound-1.7.2-py3.7.egg/bloodhound/ad/domain.py", line 675, in load_cachefile
  File "/usr/local/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.7/codecs.py", line 701, in read
    return self.reader.read(size)
  File "/usr/local/lib/python3.7/codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 8: invalid start byte`

**Comment by dirkjanm** [comment]
hey, the cachefile is for cached collection data, and expects a JSON file. to specify the CCACHE file, you can use the regular impacket way of specifying it via the `KRB5CCNAME` environment variable.
