### ISSUE TITLE
Bloodhound Issue DNS

### ISSUE THREAD

**Issue by rahulkakodiya1910** [dirkjanm/BloodHound.py#205]
Hi I am getting error while running bloodhound. Please find the error below with screenshot.

Traceback (most recent call last):
  File "/usr/bin/bloodhound-python", line 33, in <module>
    sys.exit(load_entry_point('bloodhound==1.7.2', 'console_scripts', 'bloodhound-python')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bloodhound/__init__.py", line 308, in main
    ad.dns_resolve(domain=args.domain, options=args)
  File "/usr/lib/python3/dist-packages/bloodhound/ad/domain.py", line 759, in dns_resolve
    q = self.dnsresolver.query(kquery, 'SRV', tcp=self.dns_tcp)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/dns/resolver.py", line 1089, in query
    return self.resolve(qname, rdtype, rdclass, tcp, source,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/dns/resolver.py", line 584, in next_request
    raise NXDOMAIN(qnames=self.qnames_to_try,
dns.resolver.NXDOMAIN: The DNS query name does not exist: _kerberos._tcp.dc._msdcs.

<img width="689" alt="error" src="https://github.com/user-attachments/assets/112a8cae-84cb-465d-93f8-8bb7f8f471d7" />

**Comment by GeriHB** [comment]
Same issue here

**Comment by dirkjanm** [comment]
You are not specifying a domain to query. Adding `-d pezz.local` would probably solve the issue. Your values for `-dc` and `-gc` also don't make any sense, these expect full hostnames includig the domain part.

**Comment by derekkddj** [comment]
same error here
