### ISSUE TITLE
Can't connect with LDAP Signing / Channel Binding enabled

### ISSUE THREAD

**Issue by corsch** [dirkjanm/BloodHound.py#55]
Since I've enabled LDAP Signing on our Domain Controllers I'm no longer able to run bloodhound.py

> python3 bloodhound.py -u bloodhound@domain.local -d domain.local -c all -v
> Password:
> DEBUG: Resolved collection methods: acl, group, session, localadmin, psremote, rdp, dcom, objectprops, trusts
> DEBUG: Using DNS to retrieve domain information
> DEBUG: Querying domain controller information from DNS
> DEBUG: Using domain hint: domain.local
> INFO: Found AD domain: domain.local
> DEBUG: Found primary DC: dc01.domain.local
> DEBUG: Found Global Catalog server: dc01.domain.local
> DEBUG: Using LDAP server: dc01.domain.local
> DEBUG: Using base DN: DC=domain,DC=local
> INFO: Connecting to LDAP server: dc01.domain.local
> DEBUG: Authenticating to LDAP server
> WARNING: LDAP Authentication is refused because LDAP signing is enabled. Trying to connect over LDAPS instead...
> DEBUG: Authenticating to LDAP server
> ERROR: Failure to authenticate with LDAP! Error 80090346: LdapErr: DSID-0C09069E, comment: AcceptSecurityContext error, data 80090346, v2580
> Traceback (most recent call last):
>   File "/root/Documents/tools/BloodHound.py/bloodhound.py", line 5, in <module>
>     bloodhound.main()
>   File "/root/Documents/tools/BloodHound.py/bloodhound/__init__.py", line 284, in main
>     bloodhound.run(collect=collect,
>   File "/root/Documents/tools/BloodHound.py/bloodhound/__init__.py", line 72, in run
>     self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
>   File "/root/Documents/tools/BloodHound.py/bloodhound/ad/domain.py", line 394, in prefetch_info
>     self.get_objecttype()
>   File "/root/Documents/tools/BloodHound.py/bloodhound/ad/domain.py", line 226, in get_objecttype
>     sresult = self.ldap.extend.standard.paged_search(self.ldap.server.info.other['schemaNamingContext'][0],
> AttributeError: 'NoneType' object has no attribute 'extend'

Does anyone else have this issue too?

**Comment by dirkjanm** [comment]
Is ldap channel binding set to required? That may cause the issue when connecting over TLS

**Comment by corsch** [comment]
yes it is

**Comment by dirkjanm** [comment]
Interesting. I imagine this is a limitation of the ldap3 library since it doesn't support channel binding nor signing. I'd have to look if we can add it to that library. There isn't really another way to fix it.

**Comment by epictendies** [comment]
Where did this land? Noting that the project hasn't been updated for Bloodhound 4.x - I still use this from time to time and signing is currently breaking things.,

**Comment by corsch** [comment]
I'm also looking forward for a new version :)

The "good" thing is, that Microsoft is still not enforcing signing and channel binding :D

**Comment by cyberlama** [comment]
Hello - I came across this issue recently with the same error.   I went searching through the ldap3 docs and if i'm reading this right there might be supporting for signing now- https://ldap3.readthedocs.io/en/latest/ssltls.html?highlight=channel%20binding

DEBUG: Authenticating to LDAP server
WARNING: LDAP Authentication is refused because LDAP signing is enabled. Trying to connect over LDAPS instead...
DEBUG: Authenticating to LDAP server
ERROR: Failure to authenticate with LDAP! Error 80090346: LdapErr: DSID-0C0906B5, comment: AcceptSecurityContext error, data 80090346, v4563
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/bloodhound/__init__.py", line 297, in main
    bloodhound.run(collect=collect,
  File "/usr/local/lib/python3.9/dist-packages/bloodhound/__init__.py", line 73, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
  File "/usr/local/lib/python3.9/dist-packages/bloodhound/ad/domain.py", line 393, in prefetch_info
    self.get_objecttype()
  File "/usr/local/lib/python3.9/dist-packages/bloodhound/ad/domain.py", line 225, in get_objecttype
    sresult = self.ldap.extend.standard.paged_search(self.ldap.server.info.other['schemaNamingContext'][0],
AttributeError: 'NoneType' object has no attribute 'extend'

**Comment by dirkjanm** [comment]
This is still unsupported by ldap3. Since signing is not only used in the bind stage but with every ldap message sent, this would require quite some modifications to the library. Channel binding would probably be slightly easier, but since you can't use LDAPS then it's still the same problem.

Switching out the core ldap library to a different one isn't exactly easy either, there would be additional dependencies and many things breaking probably.

**Comment by aconite33** [comment]
@dirkjanm I've been able to use ly4k version of ldap3 to work with impacket. I'm still having some trouble with bloodhound.py, but at least I got getTGT.py to work with Impacket.

Here is the issue and links:

Original Issue: https://github.com/fortra/impacket/issues/884
PR: https://github.com/fortra/impacket/pull/1652
Repository: https://github.com/ly4k/ldap3

**Comment by aconite33** [comment]
From Bloodhound.py with ldap3.py from ly4k:

```bash
# snippet
pyasn1.error.PyAsn1Error: <TagSet object, tags 0:32:16-64:32:30> not in asn1Spec: <AS_REP schema object, tagSet=<TagSet object, tags 0:32:16-64:32:11>, subtypeSpec=<ConstraintsIntersection object>, componentType=<NamedTypes object, types <NamedType object, type pvno=<Integer schema object, tagSet <TagSet object, tags 0:0:2-128:32:0>, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object,
```

Impacket before using l4yk:

```bash
# snippet
<TagSet object, tags 0:32:16-64:32:30> not in asn1Spec: <AS_REP schema object, tagSet=<TagSet object, tags 0:32:16-64:32:11>, subtypeSpec=<ConstraintsIntersection object>, componentType=<NamedTypes object, types <NamedType object, type pvno=<Integer schema object, tagSet <TagSet object, tags 0:0:2-128:32:0>, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object,
```

Impacket after Ldap3.py from Ly4k:

```bash
getTGT.py 'domain.example/user1' -dc-ip 192.168.1.1
[*] Saving ticket in user1.ccache
```

**Comment by dirkjanm** [comment]
There's a PR which adds support for that, maybe that would help you in the right direction: https://github.com/dirkjanm/BloodHound.py/pull/148

**Comment by aconite33** [comment]
Correct, that is the PR I linked in my comment. While I am able to make this work with impacket to get a TGT, I am unable to get it to work with Bloodhound.py.

When I switch out the ldap3 in your setup.py for ly4k, I still am unable to get Bloodhound.py to authenticate properly and pull a TGT. It tries to fall back to NTLM authentication, but in my current configuration with LDAP channel binding, this seems to not work with Bloodhound.py, but yet I am able to do it with Impacket.

I've even generated the CCACHE within Impacket and tried to use that within Bloodhound.py and I'm still running into issues.

**Comment by 011Mostafa011** [comment]
In case you stumbled onto this  issue like me then maybe try sync  your local machines clock with the LDAP server. 
Sudo ntpdate -s <ServerIP>
Since if clock not in sync LDAP signing is enforced.

**Comment by dirkjanm** [comment]
* LDAP signing will be unsupported for the near future, has to be supported by the upstream ldap3 library for us to use it
* LDAP channel binding with Kerberos is now built in natively to BloodHound python (both CE and Legacy)
* LDAP channel binding with NTLM works with a custom `ldap3` version, either the one from ly4k or the one maintained here: https://github.com/ThePirateWhoSmellsOfSunflowers/ldap3/tree/bleeding_edge / https://pypi.org/project/ldap3-bleeding-edge/
